-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 16:12:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT(20) NOT NULL,
  `order_id` INT(20) NULL,
  `client_id` INT(20) NULL,
  `prod_id` INT(20) NULL,
  `product_desc` VARCHAR(50) NULL,
  `product_name` VARCHAR(50) NULL,
  `product_type` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shipper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shipper` (
  `id` INT(20) NOT NULL,
  `product_id` INT(20) NULL,
  `shipper_lname` VARCHAR(20) NULL,
  `shipper_fname` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_shipper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_has_shipper` (
  `product_id` INT(20) NOT NULL,
  `shipper_id` INT(20) NOT NULL,
  PRIMARY KEY (`product_id`, `shipper_id`),
  INDEX `fk_product_has_shipper_shipper1_idx` (`shipper_id` ASC),
  INDEX `fk_product_has_shipper_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_shipper_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_shipper_shipper1`
    FOREIGN KEY (`shipper_id`)
    REFERENCES `mydb`.`shipper` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
